### ISSUE TITLE
Some generator expressions are not supported

### ISSUE THREAD

**Issue by ConaII** [billythegoat356/Hyperion#10]
```py
(pygame.mixer.Channel(i).pause() for i in range(0,4))
```

Error:
```
    module utils.funcs raised an Exception:
     expected an indented block (<string>, line 2519)
Traceback (most recent call last):
  File "{path}\obfuscated\utils\funcs.py", line 239, in <module>
    System(Math = -9108 + 39590)._negative(_detectvar = _math.Random + 6311) 
  File "<string>", line 2519
    (pygame.mixer.Channel(i).pause()for i in range(IlIIllIIIlllIIIlllIlIll,OOO0oO0oooOoOooOOoO00ooO0))
                                                                                                     ^
IndentationError: expected an indented block
 ^^^

**Comment by ConaII** [comment]
```py
    # Any of these will work perfectly:
    print("Starting Test")
    print(" Test1: {}")
    x = {print(i) for i in range(2)}
    print(" Test2: []")
    y = [print(i) for i in range(2)]
    print(" Test3: ()")
    z = (print(i) for i in range(2))
    print("Success!")
```

```
{path}\obfuscated>py test.py

    Starting Test
     Test1: {}
    0
    1
     Test2: []
    0
    1
     Test3: ()
    Success!
```
