### ISSUE TITLE
File not found.

### ISSUE THREAD

**Issue by therealOri** [billythegoat356/Hyperion#7]
When dragging and dropping a file into the terminal to be obfuscated it will firstly spit out an invalid file error, unless you press backspace once. (I have a fix for that and have manually edited that on my end with the following code) `.replace('\\', ' ').strip()`

```python
file = input(stage(f"Drag the file you want to obfuscate {dark}-> {Col.reset}", "?", col2 = bpurple)).replace('\\', ' ').strip().replace('"','').replace("'","")
```
__ __

<br />
<br />

Now the error I'm encountering is:
```bash
Traceback (most recent call last):
  File "/home/ori/Desktop/Hyperion/hyperion.py", line 1003, in <module>
    main()
  File "/home/ori/Desktop/Hyperion/hyperion.py", line 992, in main
    with open(f'obf-{filename}', mode='w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'obf-/home/ori/Desktop/Hyperion/test.py'
```
> The issue here is that it's using the path to the file instead of the file name and obviously `obf-/home/ori/Desktop/Hyperion/test.py'` isn't going to exist.

The main issue and the reason this error happens is because "`filename`" isn't a valid file and is instead a path. (Idk how you managed to do this or make this happen..but man is it weird.)
__ __

<br />
<br />

# Steps to reproduce
1 - Start Hyperion
2 - Drag and drop .py file into terminal window. (After using my "patch")
3 - Don't skip anything and type "n" when prompted.
4 - Oof (error happens)
__ __
Notes:
> All of the code I am having issues with is in the main() function.

**Comment by therealOri** [comment]
Hmm, I think I may know what the issue is.

It's working with a windows path system but not linux/unix.
It is trying to split `\\` when linux/unix is `/`

Idk, I'm gonna mess around with that and see what happens.

**Comment by therealOri** [comment]
I have made a pull request with a fix for some of my issues.

A fixed version can be found [Here](https://github.com/therealOri/Hyperion) in case my pull request isn't accepted.
